version: '3.1'

services:
  # TODO: Add worker service
  metadata:
    image: ghcr.io/hawks-atlanta/metadata-scala:latest
    container_name: metadata
    restart: on-failure
    ports:
      - "127.0.0.1:8081:8080"
    env:
      DATABASE_HOST: postgres-db
      DATABASE_PORT: '5432'
      DATABASE_NAME: database
      DATABASE_USER: username
      DATABASE_PASSWORD: password
  authentication:
    image: ghcr.io/hawks-atlanta/authentication-go:latest
    container_name: authentication
    restart: on-failure
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      DATABASE_ENGINE: postgres
      DATABASE_DSN: "host=postgres-db user=username password=password dbname=database port=5432 sslmode=disable"
  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    restart: on-failure
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database
    volumes:
      # - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres-volume:/var/lib/postgresql/data

  postgres-admin:
    image: dpage/pgadmin4
    container_name: postgres-admin
    ports:
      - "127.0.0.1:5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres@postgres.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
    depends_on:
      - postgres-db