/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gateway;

import javax.xml.ws.Endpoint;

public class App
{
	public String getGreeting () { return "Starting gateway..."; }

	public static void main (String[] args)
	{
		System.out.println (new App ().getGreeting ());

		Endpoint.publish (
			"http://localhost:8080/sampleservice", new SampleServiceImp ());
	}
}
